### ISSUE TITLE
Values are incorrect

### ISSUE THREAD

**Issue by xpoke** [fnvhash/fnv-calculator-online#1]
Hey, I tried using this to debug my own code running FNV-1a (specifically 32 bit), and got very confused when the values did not match no matter what.

After a while and lots of double checking I came to the conclusion that the values are not passed correctly between the input and the FNV algorithm.
Using the webpage with the ascii input 'a' (x'61'), the FNV-1a 32bit output is x'e30a5ca8'.
On my own code, and also on other online tools ([One](https://www.tools4noobs.com/online_tools/hash/), [Two](http://www.nitrxgen.net/hashgen/)), the output is x'e40c292c'. The same behavior happens on 64 bit and probably on other sizes.

Using the input x'00' for 32 bits, the fnv-1a algorithm should do this function:
Hash = xor(offset,x'00') \* prime % (2^bits) = offset \* prime % (2^bits) = 2166136261 \* 16777619 % (2^32) = 84696351 = x'050c5d1f', however the calculator outputs x'0cc04282' instead.

Also, in FNV-1a 32bit, the words "liquid" and "costarring" [should collide](http://programmers.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed) (on x'5e4daa9d'), but they don't even collide on the calculator.

**Comment by stuartpb** [comment]
Agreed - the [zero hash challenge](http://www.isthe.com/chongo/tech/comp/fnv/#zero-hash) results do not yield zero in this implementation (ie `eSN.1` does not hash to 0 with 32-bit FNV-1).

**Comment by siriobalmelli** [comment]
Ran into this as well.
The string "the quick brown fox jumped over the lazy dog" should FNV1a_64 to 0x4fb124b03ec8f8f8 and instead hashes to 0x5596439444e3e93a

**Comment by nqv** [comment]
Looks like the project is no longer being maintained. I've created a simple alternative at https://nqv.github.io/fnv/

**Comment by cheezypoofs** [comment]
Dang, I wish I would have seen this issue before I wasted time on this. The fnv project itself has test vectors. None of the ones I tried work on this site.

http://isthe.com/chongo/src/fnv/test_fnv.c

**Comment by siriobalmelli** [comment]
If it helps, my library has an 'fnvsum' utility which will hash a file or input from stdin.
... and both the fnv implementation and the utility have tests ;)

https://github.com/siriobalmelli/nonlibc#fast-reliable-32-bit-and-64-bit-hashing---fnvh

**Comment by fnvhash** [comment]
Thanks for info I will adjust the online Javascript version now.

**Comment by fnvhash** [comment]
thanks @xPoke @stuartpb   @cheezypoofs   @siriobalmelli  and @nqv   it is fixed now. I have used nqv code. Sorry this escaped my notice but glad we could fix it finally. thank you!
